# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='person_images'),
        ),
    ]
