# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20171101_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='photo',
        ),
    ]
