# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
